# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task13' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task13
  pod 'SkyFloatingLabelTextField', '~> 3.0'
end
